In [ ]:
## Loading Directories

In [1]:
import pandas as pd                    # data analysis
import numpy as np                     # scientific calculations
import seaborn as sns                  # Statistical process
import matplotlib.pyplot as plt        # plotting
%matplotlib inline


In [2]:
## Reading the data file

In [3]:
pf_data = pd.read_csv('Student_Pass_Fail.csv')
print(pf_data)
pf_data.head()

     Self_Study_Daily  Tution_Monthly  Pass_Or_Fail
0                   7              27             1
1                   2              43             0
2                   7              26             1
3                   8              29             1
4                   3              42             0
..                ...             ...           ...
995                 6              22             1
996                 9              30             1
997                 3              39             0
998                 7              25             1
999                 5              37             0

[1000 rows x 3 columns]


Self_Study_Daily  Tution_Monthly  Pass_Or_Fail
0                 7              27             1
1                 2              43             0
2                 7              26             1
3                 8              29             1
4                 3              42             0

In [4]:
## Defining Independent and dependent variables

In [5]:
x = pf_data.drop('Pass_Or_Fail',axis = 1)
y = pf_data.Pass_Or_Fail


In [6]:
## Importing Logistic regression model

In [7]:
from sklearn import metrics 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [8]:
logistic_regression = LogisticRegression()

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=4)

In [10]:
logistic_regression.fit(x_train,y_train)
print(logistic_regression.intercept_)
print(logistic_regression.coef_)

[5.11141955]
[[ 2.43697194 -0.74397963]]


In [11]:
y_pred = logistic_regression.predict(x_test)
print(y_pred)

[1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 0 1
 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1
 1 0 1 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0
 1 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1
 1 0 1 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0
 0 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 1 0
 1 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 1]


In [12]:
## Checking Accuracy

In [13]:
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy_percentage = 100 * accuracy
accuracy_percentage

96.8

In [14]:
## Classification Report

In [15]:
from sklearn.metrics import classification_report
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      0.94      0.97       128\n           1       0.94      1.00      0.97       122\n\n    accuracy                           0.97       250\n   macro avg       0.97      0.97      0.97       250\nweighted avg       0.97      0.97      0.97       250\n'

In [16]:
##  Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[120,   8],
       [  0, 122]], dtype=int64)

In [18]:
## Accuracy Score

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.968

In [20]:
## Prediction on new data

In [24]:
New_students={'Self_Study_Daily':[8,5,10,3,12,8,6],'Tution_Monthly':[20,30,60,40,70,29,22]}
df2 = pd.DataFrame(New_students,columns= ['Self_Study_Daily', 'Tution_Monthly'])
y_pred=logistic_regression.predict(df2)
print (df2)
print (y_pred)

   Self_Study_Daily  Tution_Monthly
0                 8              20
1                 5              30
2                10              60
3                 3              40
4                12              70
5                 8              29
6                 6              22
[1 0 0 0 0 1 1]
